cursor #cecdc3
cursor_text_color #cecdc3

foreground            #cecdc3
background            #100f0f
selection_foreground  #100f0f
selection_background  #4385be
url_color             #4385be

color0   #100F0F
color1   #e34775
color2   #43be52
color3   #ede444
color4   #4285c7
color5   #002f57
color6   #4385BE
color7   #b8c0c7
color8   #73797f
color9   #ff83a8
color10  #7ce489
color11  #fff88b
color12  #5d9bd1
color13  #87c3f6
color14  #b4dcff
color15  #f6fbff
