cursor #f0f0f0
cursor_text_color #b8d9ce

foreground            #f0f0f0
background            #09070d
selection_foreground  #1e1e00
selection_background  #b8a8f0
url_color             #92eda7

color0   #130f1a
color1   #ff9872
color2   #76ed77
color3   #fff072
color4   #79e191
color5   #206d32
color6   #92eda7
color7   #e9f8ed
color8   #8e9a91
color9   #ffb89f
color10  #a5ffa6
color11  #fff5a5
color12  #abffbe
color13  #baffca
color14  #d2ffdd
color15  #f8fffa
