;;; Automatically generated by ‘recentf’ on Mon Dec 15 08:44:40 2025.

(setq recentf-list
      '(
        "~/leo/development/gerador-assinaturas/Assinatura-de-Email/src/components/SignatureEditor.jsx"
        "~/leo/development/gerador-assinaturas/Assinatura-de-Email/src/modal/HelpModal.jsx"
        "i:/Testes_Assistencia/ATE-INV-NEO-DK912/Main.js"
        "~/leo/development/dotfiles/.config/bashmacs/var/treemacs/persist.org"
        "~/leo/development/dotfiles/.config/bashmacs/init.el"
        "~/leo/development/dotfiles/.config/bashmacs/keybindings.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
