;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(evil-ex-history minibuffer-history file-name-history extended-command-history))
(setq evil-ex-history '("q"))
(setq extended-command-history '("evil-mode" "restart-emacs" "describe-font" "copilot-login" "copilot-install-server" "copilot-login" "org-reload"))
(setq evil-jumps-history 'nil)
