;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(evil-ex-history file-name-history))
(setq evil-ex-history '("w" "%s/:ensure t/ " "w"))
(setq file-name-history '("~/leo/development/dotfiles/.config/bashmacs/early-init.el" "~/leo/development/dotfiles/.config/bashmacs/init.el"))
