;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(minibuffer-history extended-command-history evil-ex-history file-name-history))
(setq minibuffer-history '("treesit-auto"))
(setq extended-command-history '("package-reinstall" "package-install" "copilot-login" "copilot-install-server" "package-reinstall"))
(setq evil-ex-history '("w" "%s/:ensure t/ " "w"))
(setq file-name-history '("~/.config/qtile/config.py" "~/.config/bashmacs/" "~/leo/development/dotfiles/.config/bashmacs/early-init.el" "~/leo/development/dotfiles/.config/bashmacs/init.el"))
(setq projectile-project-command-history '#s(hash-table test equal))
(setq evil-jumps-history '((1979 #1="/home/bashln/.config/qtile/config.py") (8925 #1#) (7080 #1#) (6856 #1#) (6605 #1#) (4526 #1#) (3214 #1#) (21444 #2="/home/bashln/.config/bashmacs/config.el") (3370 #2#)))
