[colors]
background = '#131313'
foreground = '#e2e2e2'

cursor_bg = '#fdba4b'
cursor_fg = '#131313'
cursor_border = '#fdba4b'

selection_bg = '#614000'
selection_fg = '#e2e2e2'

ansi = ['#131313', '#e2497b', '#95d66e', '#dbaf7b', '#bb8225', '#bd9552', '#fdba4b', '#abb2bf']
brights = ['#5c6370', '#e05f8d', '#a8e086', '#e8c397', '#fccd8b', '#a86a3a', '#8d7739', '#ffffff']
