[colors]
background = '#1e1e2e'
foreground = '#cdd6f4'

cursor_bg = '#cba6f7'
cursor_fg = '#1e1e2e'
cursor_border = '#cba6f7'

selection_bg = '#55307f'
selection_fg = '#cdd6f4'

ansi = ['#181825', '#e15542', '#6ed677', '#dbdb7b', '#9f6adc', '#9e88b9', '#cba6f7', '#abb2bf']
brights = ['#5c6370', '#e06c5f', '#86e08d', '#e7e897', '#e8c6ff', '#886bca', '#956bb2', '#ffffff']
