[colors.primary]
background = '#09070d'
foreground = '#f0f0f0'

[colors.selection]
text = '#f0f0f0'
background = '#5b8c7e'

[colors.cursor]
text = '#09070d'
cursor = '#92eda7'

[colors.normal]
black   = '#130f1a'
red     = '#ff9872'
green   = '#76ed77'
yellow  = '#fff072'
blue    = '#79e191'
magenta = '#206d32'
cyan    = '#92eda7'
white   = '#e9f8ed'

[colors.bright]
black   = '#8e9a91'
red     = '#ffb89f'
green   = '#a5ffa6'
yellow  = '#fff5a5'
blue    = '#abffbe'
magenta = '#baffca'
cyan    = '#d2ffdd'
white   = '#f8fffa'
