[colors]
background = '#09070d'
foreground = '#f0f0f0'

cursor_bg = '#92eda7'
cursor_fg = '#09070d'
cursor_border = '#92eda7'

selection_bg = '#5b8c7e'
selection_fg = '#f0f0f0'

ansi = ['#130f1a', '#ff9872', '#76ed77', '#fff072', '#79e191', '#206d32', '#92eda7', '#e9f8ed']
brights = ['#8e9a91', '#ffb89f', '#a5ffa6', '#fff5a5', '#abffbe', '#baffca', '#d2ffdd', '#f8fffa']
